name: Parallel Test Build
on: push
jobs:
  AddToCart-Flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npm run test:addToCart

      - name: Cypress Test report
        uses: actions/upload-artifact@v4
        with:
            name: Mochawsome HTML report - AddToCart Report
            path: cypress/reports/html

  Register-flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npm run test:registration

      - name: Cypress Test report
        uses: actions/upload-artifact@v4
        with:
             name: Mochawsome HTML report - Registration Report
             path: cypress/reports/html    